from __future__ import annotations

from typing import Any

from memframe.core.orchestrator.analytix.datetime import DateTimeOrchestrator


class DateTimeWrapper(DateTimeOrchestrator):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    async def aextract(self, column: str, field: str) -> dict[str, Any]: ...
    def extract(self, column: str, field: str) -> dict[str, Any]: ...

    async def ayear(self, column: str) -> dict[str, Any]: ...
    def year(self, column: str) -> dict[str, Any]: ...

    async def amonth(self, column: str) -> dict[str, Any]: ...
    def month(self, column: str) -> dict[str, Any]: ...

    async def aday(self, column: str) -> dict[str, Any]: ...
    def day(self, column: str) -> dict[str, Any]: ...

    async def ahour(self, column: str) -> dict[str, Any]: ...
    def hour(self, column: str) -> dict[str, Any]: ...

    async def aminute(self, column: str) -> dict[str, Any]: ...
    def minute(self, column: str) -> dict[str, Any]: ...

    async def asecond(self, column: str) -> dict[str, Any]: ...
    def second(self, column: str) -> dict[str, Any]: ...

    async def adayofweek(self, column: str) -> dict[str, Any]: ...
    def dayofweek(self, column: str) -> dict[str, Any]: ...

    async def adayofyear(self, column: str) -> dict[str, Any]: ...
    def dayofyear(self, column: str) -> dict[str, Any]: ...

    async def aweek(self, column: str) -> dict[str, Any]: ...
    def week(self, column: str) -> dict[str, Any]: ...

    async def aquarter(self, column: str) -> dict[str, Any]: ...
    def quarter(self, column: str) -> dict[str, Any]: ...

    async def afloor(self, column: str, unit: str) -> dict[str, Any]: ...
    def floor(self, column: str, unit: str) -> dict[str, Any]: ...

    async def aceil(self, column: str, unit: str) -> dict[str, Any]: ...
    def ceil(self, column: str, unit: str) -> dict[str, Any]: ...

    async def around(self, column: str, unit: str) -> dict[str, Any]: ...
    def round(self, column: str, unit: str) -> dict[str, Any]: ...

    async def atz_localize(
        self,
        column: str,
        tz: str | None,
        ambiguous: str = "raise",
        nonexistent: str = "raise",
    ) -> dict[str, Any]: ...

    def tz_localize(
        self,
        column: str,
        tz: str | None,
        ambiguous: str = "raise",
        nonexistent: str = "raise",
    ) -> dict[str, Any]: ...

    async def atz_convert(
        self,
        column: str,
        tz: str | None,
    ) -> dict[str, Any]: ...

    def tz_convert(
        self,
        column: str,
        tz: str | None,
    ) -> dict[str, Any]: ...

    async def ais_month_start(self, column: str): ...
    def is_month_start(self, column: str): ...

    async def ais_month_end(self, column: str): ...
    def is_month_end(self, column: str): ...

    async def ais_year_start(self, column: str): ...
    def is_year_start(self, column: str): ...

    async def ais_year_end(self, column: str): ...
    def is_year_end(self, column: str): ...

    async def ais_quarter_start(self, column: str): ...
    def is_quarter_start(self, column: str): ...

    async def ais_quarter_end(self, column: str): ...
    def is_quarter_end(self, column: str): ...

    async def adays_in_month(self, column: str): ...
    def days_in_month(self, column: str): ...

    async def ais_weekend(self, column: str): ...
    def is_weekend(self, column: str): ...

    async def ais_weekday(self, column: str): ...
    def is_weekday(self, column: str): ...

    async def ais_business_day(self, column: str): ...
    def is_business_day(self, column: str): ...

    async def aweek_of_month(self, column: str): ...
    def week_of_month(self, column: str): ...

    async def atimestamp(self, column: str): ...
    def timestamp(self, column: str): ...

    async def afrom_timestamp(
        self,
        column: str | None = None,
        value: float | None = None,
        tz: str | None = None,
    ): ...

    def from_timestamp(
        self,
        column: str | None = None,
        value: float | None = None,
        tz: str | None = None,
    ): ...

    async def astrftime(self, column: str, fmt: str): ...
    def strftime(self, column: str, fmt: str): ...

    async def astrptime(self, column: str, fmt: str): ...
    def strptime(self, column: str, fmt: str): ...

    async def aadd(self, column: str, interval: str): ...
    def add(self, column: str, interval: str): ...

    async def asub(self, column: str, interval: str): ...
    def sub(self, column: str, interval: str): ...

    async def areplace(self, column: str, **kwargs: Any): ...
    def replace(self, column: str, **kwargs: Any): ...

    async def anormalize(self, column: str): ...
    def normalize(self, column: str): ...

    async def aday_name(self, column: str) -> dict[str, Any]: ...
    def day_name(self, column: str) -> dict[str, Any]: ...

    async def amonth_name(self, column: str) -> dict[str, Any]: ...
    def month_name(self, column: str) -> dict[str, Any]: ...

    async def adiff(
        self,
        col1: str,
        col2: str,
        unit: str = "day",
        target_col: str | None = None,
    ) -> dict[str, Any]: ...

    def diff(
        self,
        col1: str,
        col2: str,
        unit: str = "day",
        target_col: str | None = None,
    ) -> dict[str, Any]: ...

    async def ato_datetime(
        self,
        column: str,
        format: str | None = None,
        errors: str = "raise",
        unit: str | None = None,
        tz: str | None = None,
    ) -> dict[str, Any]: ...

    def to_datetime(
        self,
        column: str,
        format: str | None = None,
        errors: str = "raise",
        unit: str | None = None,
        tz: str | None = None,
    ) -> dict[str, Any]: ...

    async def abetween(self, column: str, start: str, end: str) -> dict[str, Any]: ...
    def between(self, column: str, start: str, end: str) -> dict[str, Any]: ...

    async def abefore(self, column: str, value: str) -> dict[str, Any]: ...
    def before(self, column: str, value: str) -> dict[str, Any]: ...

    async def aafter(self, column: str, value: str) -> dict[str, Any]: ...
    def after(self, column: str, value: str) -> dict[str, Any]: ...

    async def aselect_year(self, column: str, values: Any) -> dict[str, Any]: ...
    def select_year(self, column: str, values: Any) -> dict[str, Any]: ...

    async def aselect_month(self, column: str, values: Any) -> dict[str, Any]: ...
    def select_month(self, column: str, values: Any) -> dict[str, Any]: ...

    async def aresample(
        self,
        column: str,
        freq: str,
        agg: Any = "count",
        value_columns: Any = None,
        group_by: Any = None,
        label: str = "left",
        closed: str = "left",
    ) -> dict[str, Any]: ...

    def resample(
        self,
        column: str,
        freq: str,
        agg: Any = "count",
        value_columns: Any = None,
        group_by: Any = None,
        label: str = "left",
        closed: str = "left",
    ) -> dict[str, Any]: ...

    async def aasfreq(
        self,
        column: str,
        freq: str,
        method: str | None = None,
    ) -> dict[str, Any]: ...

    def asfreq(
        self,
        column: str,
        freq: str,
        method: str | None = None,
    ) -> dict[str, Any]: ...

    async def aadd_offset(
        self,
        column: str,
        years: int = 0,
        quarters: int = 0,
        months: int = 0,
        weeks: int = 0,
        days: int = 0,
        business_day: bool = False,
        target_col: str | None = None,
    ) -> dict[str, Any]: ...

    def add_offset(
        self,
        column: str,
        years: int = 0,
        quarters: int = 0,
        months: int = 0,
        weeks: int = 0,
        days: int = 0,
        business_day: bool = False,
        target_col: str | None = None,
    ) -> dict[str, Any]: ...