# src/wrappers/groupby_window.pyi

from __future__ import annotations

from typing import Any, Dict, List, Union

from memframe.core.orchestrator.analytix.groupby_window import (
    GroupByWindowOrchestrator,
    GroupByWindow,
    GroupByRolling,
    GroupByExpanding,
    GroupByEWM,
)


class GroupByRollingWrapper(GroupByRolling):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def amean(self, column: str) -> Dict[str, Any]: ...
    def mean(self, column: str) -> Dict[str, Any]: ...
    async def asum(self, column: str) -> Dict[str, Any]: ...
    def sum(self, column: str) -> Dict[str, Any]: ...
    async def amin(self, column: str) -> Dict[str, Any]: ...
    def min(self, column: str) -> Dict[str, Any]: ...
    async def amax(self, column: str) -> Dict[str, Any]: ...
    def max(self, column: str) -> Dict[str, Any]: ...
    async def astd(self, column: str) -> Dict[str, Any]: ...
    def std(self, column: str) -> Dict[str, Any]: ...
    async def avar(self, column: str) -> Dict[str, Any]: ...
    def var(self, column: str) -> Dict[str, Any]: ...
    async def acount(self, column: str) -> Dict[str, Any]: ...
    def count(self, column: str) -> Dict[str, Any]: ...
    async def anunique(self, column: str) -> Dict[str, Any]: ...
    def nunique(self, column: str) -> Dict[str, Any]: ...
    async def afirst(self, column: str) -> Dict[str, Any]: ...
    def first(self, column: str) -> Dict[str, Any]: ...
    async def alast(self, column: str) -> Dict[str, Any]: ...
    def last(self, column: str) -> Dict[str, Any]: ...
    async def aquantile(self, column: str, q: float = ...) -> Dict[str, Any]: ...
    def quantile(self, column: str, q: float = ...) -> Dict[str, Any]: ...
    async def arank(self, column: str) -> Dict[str, Any]: ...
    def rank(self, column: str) -> Dict[str, Any]: ...
    async def asem(self, column: str) -> Dict[str, Any]: ...
    def sem(self, column: str) -> Dict[str, Any]: ...
    async def aagg(self, column: str, funcs: List[str], **kwargs: Any) -> Dict[str, Any]: ...
    def agg(self, column: str, funcs: List[str], **kwargs: Any) -> Dict[str, Any]: ...


class GroupByExpandingWrapper(GroupByExpanding):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def asum(self, column: str) -> Dict[str, Any]: ...
    def sum(self, column: str) -> Dict[str, Any]: ...
    async def amean(self, column: str) -> Dict[str, Any]: ...
    def mean(self, column: str) -> Dict[str, Any]: ...
    async def amin(self, column: str) -> Dict[str, Any]: ...
    def min(self, column: str) -> Dict[str, Any]: ...
    async def amax(self, column: str) -> Dict[str, Any]: ...
    def max(self, column: str) -> Dict[str, Any]: ...
    async def astd(self, column: str) -> Dict[str, Any]: ...
    def std(self, column: str) -> Dict[str, Any]: ...
    async def avar(self, column: str) -> Dict[str, Any]: ...
    def var(self, column: str) -> Dict[str, Any]: ...
    async def acount(self, column: str) -> Dict[str, Any]: ...
    def count(self, column: str) -> Dict[str, Any]: ...
    async def anunique(self, column: str) -> Dict[str, Any]: ...
    def nunique(self, column: str) -> Dict[str, Any]: ...
    async def afirst(self, column: str) -> Dict[str, Any]: ...
    def first(self, column: str) -> Dict[str, Any]: ...
    async def alast(self, column: str) -> Dict[str, Any]: ...
    def last(self, column: str) -> Dict[str, Any]: ...
    async def aquantile(self, column: str, q: float = ...) -> Dict[str, Any]: ...
    def quantile(self, column: str, q: float = ...) -> Dict[str, Any]: ...
    async def arank(self, column: str) -> Dict[str, Any]: ...
    def rank(self, column: str) -> Dict[str, Any]: ...
    async def asem(self, column: str) -> Dict[str, Any]: ...
    def sem(self, column: str) -> Dict[str, Any]: ...
    async def aagg(self, column: str, funcs: List[str], **kwargs: Any) -> Dict[str, Any]: ...
    def agg(self, column: str, funcs: List[str], **kwargs: Any) -> Dict[str, Any]: ...


class GroupByEWMWrapper(GroupByEWM):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def amean(self, column: str) -> Dict[str, Any]: ...
    def mean(self, column: str) -> Dict[str, Any]: ...
    async def asum(self, column: str) -> Dict[str, Any]: ...
    def sum(self, column: str) -> Dict[str, Any]: ...
    async def astd(self, column: str) -> Dict[str, Any]: ...
    def std(self, column: str) -> Dict[str, Any]: ...
    async def avar(self, column: str) -> Dict[str, Any]: ...
    def var(self, column: str) -> Dict[str, Any]: ...
    async def aagg(self, column: str, funcs: List[str]) -> Dict[str, Any]: ...
    def agg(self, column: str, funcs: List[str]) -> Dict[str, Any]: ...


class GroupByWindowWrapper(GroupByWindow):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def rolling(self, window: int, order_by: Union[str, List[str]] = ...) -> GroupByRollingWrapper: ...
    def expanding(self, min_periods: int = ..., order_by: Union[str, List[str]] = ...) -> GroupByExpandingWrapper: ...
    def ewm(self, order_by=..., com=..., span=..., halflife=..., alpha=..., adjust=..., ignore_na=..., min_periods=...) -> GroupByEWMWrapper: ...


class GroupByWindowStatsWrapper(GroupByWindowOrchestrator):
    def __init__(self, memframe_ops_instance: Any) -> None: ...
    async def arolling(
        self,
        column: str,
        window: int,
        func: Union[str, List[str]],
        group_cols: Union[str, List[str]],
        order_by: Union[str, List[str]] = ...,
        q: float = ...,
    ) -> Dict[str, Any]: ...
    def rolling(
        self,
        column: str,
        window: int,
        func: Union[str, List[str]],
        group_cols: Union[str, List[str]],
        order_by: Union[str, List[str]] = ...,
        q: float = ...,
    ) -> Dict[str, Any]: ...
    async def aexpanding(
        self,
        column: str,
        func: Union[str, List[str]],
        group_cols: Union[str, List[str]],
        order_by: Union[str, List[str]] = ...,
        q: float = ...,
        min_periods: int = ...,
    ) -> Dict[str, Any]: ...
    def expanding(
        self,
        column: str,
        func: Union[str, List[str]],
        group_cols: Union[str, List[str]],
        order_by: Union[str, List[str]] = ...,
        q: float = ...,
        min_periods: int = ...,
    ) -> Dict[str, Any]: ...
    async def aewm(
        self,
        column: str,
        group_cols: Union[str, List[str]],
        order_by: Union[str, List[str]] = ...,
        com: float = ...,
        span: float = ...,
        halflife: float = ...,
        alpha: float = ...,
        adjust: bool = ...,
        ignore_na: bool = ...,
        min_periods: int = ...,
        func: Union[str, List[str]] = ...,
    ) -> Dict[str, Any]: ...
    def ewm(
        self,
        column: str,
        group_cols: Union[str, List[str]],
        order_by: Union[str, List[str]] = ...,
        com: float = ...,
        span: float = ...,
        halflife: float = ...,
        alpha: float = ...,
        adjust: bool = ...,
        ignore_na: bool = ...,
        min_periods: int = ...,
        func: Union[str, List[str]] = ...,
    ) -> Dict[str, Any]: ...
    def groupby(self, *columns: str) -> GroupByWindowWrapper: ...