from typing import Any, Dict, List, Optional, Union


class GroupByWrapper:
    group_cols: List[str]

    async def aagg(
        self,
        agg_dict: Dict[str, List[str]],
        new_table: Optional[str] = ...,
        map_feature: bool = ...,
    ) -> Dict[str, Any]: ...

    def agg(
        self,
        agg_dict: Dict[str, List[str]],
        new_table: Optional[str] = ...,
        map_feature: bool = ...,
    ) -> Dict[str, Any]: ...

    async def asum(self, column: str) -> Dict[str, Any]: ...
    def sum(self, column: str) -> Dict[str, Any]: ...

    async def amean(self, column: str) -> Dict[str, Any]: ...
    def mean(self, column: str) -> Dict[str, Any]: ...

    async def amin(self, column: str) -> Dict[str, Any]: ...
    def min(self, column: str) -> Dict[str, Any]: ...

    async def amax(self, column: str) -> Dict[str, Any]: ...
    def max(self, column: str) -> Dict[str, Any]: ...

    async def acount(self, column: str) -> Dict[str, Any]: ...
    def count(self, column: str) -> Dict[str, Any]: ...

    async def amedian(self, column: str) -> Dict[str, Any]: ...
    def median(self, column: str) -> Dict[str, Any]: ...

    async def amode(self, column: str) -> Dict[str, Any]: ...
    def mode(self, column: str) -> Dict[str, Any]: ...

    async def astd(self, column: str) -> Dict[str, Any]: ...
    def std(self, column: str) -> Dict[str, Any]: ...

    async def avar(self, column: str) -> Dict[str, Any]: ...
    def var(self, column: str) -> Dict[str, Any]: ...

    async def asem(self, column: str) -> Dict[str, Any]: ...
    def sem(self, column: str) -> Dict[str, Any]: ...

    async def anunique(self, column: str) -> Dict[str, Any]: ...
    def nunique(self, column: str) -> Dict[str, Any]: ...

    async def arange(self, column: str) -> Dict[str, Any]: ...
    def range(self, column: str) -> Dict[str, Any]: ...

    async def aproduct(self, column: str) -> Dict[str, Any]: ...
    def product(self, column: str) -> Dict[str, Any]: ...

    async def aevent_rate(
        self,
        datetime_col: str,
        unit: str = ...,
        new_table: Optional[str] = ...,
    ) -> Dict[str, Any]: ...

    def event_rate(
        self,
        datetime_col: str,
        unit: str = ...,
        new_table: Optional[str] = ...,
    ) -> Dict[str, Any]: ...


class GroupByStatsWrapper:
    def __init__(self, memframe_ops_instance) -> None: ...

    async def aagg(
        self,
        group_cols: Union[str, List[str]],
        agg_dict: Dict[str, List[str]],
        new_table: Optional[str] = ...,
        map_feature: bool = ...,
    ) -> Dict[str, Any]: ...

    def agg(
        self,
        group_cols: Union[str, List[str]],
        agg_dict: Dict[str, List[str]],
        new_table: Optional[str] = ...,
        map_feature: bool = ...,
    ) -> Dict[str, Any]: ...

    async def aevent_rate(
        self,
        group_cols: Union[str, List[str]],
        datetime_col: str,
        unit: str = ...,
        new_table: Optional[str] = ...,
    ) -> Dict[str, Any]: ...

    def event_rate(
        self,
        group_cols: Union[str, List[str]],
        datetime_col: str,
        unit: str = ...,
        new_table: Optional[str] = ...,
    ) -> Dict[str, Any]: ...

    def groupby(
        self,
        *columns: str,
    ) -> GroupByWrapper: ...


GroupbyStatsAccessor = GroupByStatsWrapper