from __future__ import annotations

from typing import Any


class BarPolarWrapper:
    """Public sync + async bar polar (wind rose) plotting interface."""


    async def abar_polar(
        self,
        *,
        r: Any = ...,
        theta: Any = ...,
        color: Any = ...,
        pattern_shape: Any = ...,
        hover_name: Any = ...,
        hover_data: Any = ...,
        custom_data: Any = ...,
        base: Any = ...,
        animation_frame: Any = ...,
        animation_group: Any = ...,
        category_orders: Any = ...,
        labels: Any = ...,
        color_discrete_sequence: Any = ...,
        color_discrete_map: Any = ...,
        color_continuous_scale: Any = ...,
        pattern_shape_sequence: Any = ...,
        pattern_shape_map: Any = ...,
        range_color: Any = ...,
        color_continuous_midpoint: Any = ...,
        barnorm: str | None = ...,
        barmode: str = ...,
        direction: str = ...,
        start_angle: int = ...,
        range_r: Any = ...,
        range_theta: Any = ...,
        log_r: bool = ...,
        title: str | None = ...,
        subtitle: str | None = ...,
        template: str | None = ...,
        width: int | None = ...,
        height: int | None = ...,
        **kwargs: Any,
    ) -> Any: ...

    def __call__(
        self,
        *,
        r: Any = ...,
        theta: Any = ...,
        color: Any = ...,
        pattern_shape: Any = ...,
        hover_name: Any = ...,
        hover_data: Any = ...,
        custom_data: Any = ...,
        base: Any = ...,
        animation_frame: Any = ...,
        animation_group: Any = ...,
        category_orders: Any = ...,
        labels: Any = ...,
        color_discrete_sequence: Any = ...,
        color_discrete_map: Any = ...,
        color_continuous_scale: Any = ...,
        pattern_shape_sequence: Any = ...,
        pattern_shape_map: Any = ...,
        range_color: Any = ...,
        color_continuous_midpoint: Any = ...,
        barnorm: str | None = ...,
        barmode: str = ...,
        direction: str = ...,
        start_angle: int = ...,
        range_r: Any = ...,
        range_theta: Any = ...,
        log_r: bool = ...,
        title: str | None = ...,
        subtitle: str | None = ...,
        template: str | None = ...,
        width: int | None = ...,
        height: int | None = ...,
        **kwargs: Any,
    ) -> Any: ...

    def bar_polar(
        self,
        *,
        r: Any = ...,
        theta: Any = ...,
        color: Any = ...,
        pattern_shape: Any = ...,
        hover_name: Any = ...,
        hover_data: Any = ...,
        custom_data: Any = ...,
        base: Any = ...,
        animation_frame: Any = ...,
        animation_group: Any = ...,
        category_orders: Any = ...,
        labels: Any = ...,
        color_discrete_sequence: Any = ...,
        color_discrete_map: Any = ...,
        color_continuous_scale: Any = ...,
        pattern_shape_sequence: Any = ...,
        pattern_shape_map: Any = ...,
        range_color: Any = ...,
        color_continuous_midpoint: Any = ...,
        barnorm: str | None = ...,
        barmode: str = ...,
        direction: str = ...,
        start_angle: int = ...,
        range_r: Any = ...,
        range_theta: Any = ...,
        log_r: bool = ...,
        title: str | None = ...,
        subtitle: str | None = ...,
        template: str | None = ...,
        width: int | None = ...,
        height: int | None = ...,
        **kwargs: Any,
    ) -> Any: ...