from __future__ import annotations

from typing import Any


class BarWrapper:
    """Public sync + async bar plotting interface."""
    
    async def abar(
        self,
        *,
        x: Any = ...,
        y: Any = ...,
        color: Any = ...,
        pattern_shape: Any = ...,
        facet_row: Any = ...,
        facet_col: Any = ...,
        facet_col_wrap: int = ...,
        facet_row_spacing: float | None = ...,
        facet_col_spacing: float | None = ...,
        hover_name: Any = ...,
        hover_data: Any = ...,
        custom_data: Any = ...,
        text: Any = ...,
        base: Any = ...,
        error_x: Any = ...,
        error_x_minus: Any = ...,
        error_y: Any = ...,
        error_y_minus: Any = ...,
        animation_frame: Any = ...,
        animation_group: Any = ...,
        category_orders: Any = ...,
        labels: Any = ...,
        color_discrete_sequence: Any = ...,
        color_discrete_map: Any = ...,
        color_continuous_scale: Any = ...,
        pattern_shape_sequence: Any = ...,
        pattern_shape_map: Any = ...,
        range_color: Any = ...,
        color_continuous_midpoint: Any = ...,
        opacity: float | None = ...,
        orientation: str | None = ...,
        barmode: str = ...,
        log_x: bool = ...,
        log_y: bool = ...,
        range_x: Any = ...,
        range_y: Any = ...,
        text_auto: bool | str = ...,
        title: str | None = ...,
        subtitle: str | None = ...,
        template: str | None = ...,
        width: int | None = ...,
        height: int | None = ...,
        **kwargs: Any,
    ) -> Any: ...

    def __call__(
        self,
        *,
        x: Any = ...,
        y: Any = ...,
        color: Any = ...,
        pattern_shape: Any = ...,
        facet_row: Any = ...,
        facet_col: Any = ...,
        facet_col_wrap: int = ...,
        facet_row_spacing: float | None = ...,
        facet_col_spacing: float | None = ...,
        hover_name: Any = ...,
        hover_data: Any = ...,
        custom_data: Any = ...,
        text: Any = ...,
        base: Any = ...,
        error_x: Any = ...,
        error_x_minus: Any = ...,
        error_y: Any = ...,
        error_y_minus: Any = ...,
        animation_frame: Any = ...,
        animation_group: Any = ...,
        category_orders: Any = ...,
        labels: Any = ...,
        color_discrete_sequence: Any = ...,
        color_discrete_map: Any = ...,
        color_continuous_scale: Any = ...,
        pattern_shape_sequence: Any = ...,
        pattern_shape_map: Any = ...,
        range_color: Any = ...,
        color_continuous_midpoint: Any = ...,
        opacity: float | None = ...,
        orientation: str | None = ...,
        barmode: str = ...,
        log_x: bool = ...,
        log_y: bool = ...,
        range_x: Any = ...,
        range_y: Any = ...,
        text_auto: bool | str = ...,
        title: str | None = ...,
        subtitle: str | None = ...,
        template: str | None = ...,
        width: int | None = ...,
        height: int | None = ...,
        **kwargs: Any,
    ) -> Any: ...

    def bar(
        self,
        *,
        x: Any = ...,
        y: Any = ...,
        color: Any = ...,
        pattern_shape: Any = ...,
        facet_row: Any = ...,
        facet_col: Any = ...,
        facet_col_wrap: int = ...,
        facet_row_spacing: float | None = ...,
        facet_col_spacing: float | None = ...,
        hover_name: Any = ...,
        hover_data: Any = ...,
        custom_data: Any = ...,
        text: Any = ...,
        base: Any = ...,
        error_x: Any = ...,
        error_x_minus: Any = ...,
        error_y: Any = ...,
        error_y_minus: Any = ...,
        animation_frame: Any = ...,
        animation_group: Any = ...,
        category_orders: Any = ...,
        labels: Any = ...,
        color_discrete_sequence: Any = ...,
        color_discrete_map: Any = ...,
        color_continuous_scale: Any = ...,
        pattern_shape_sequence: Any = ...,
        pattern_shape_map: Any = ...,
        range_color: Any = ...,
        color_continuous_midpoint: Any = ...,
        opacity: float | None = ...,
        orientation: str | None = ...,
        barmode: str = ...,
        log_x: bool = ...,
        log_y: bool = ...,
        range_x: Any = ...,
        range_y: Any = ...,
        text_auto: bool | str = ...,
        title: str | None = ...,
        subtitle: str | None = ...,
        template: str | None = ...,
        width: int | None = ...,
        height: int | None = ...,
        **kwargs: Any,
    ) -> Any: ...