from __future__ import annotations

from typing import Any


class Scatter3DWrapper:
    """Public sync + async 3D scatter plotting interface."""

    def __init__(self, memframe_ops_instance) -> None: ...

    
    async def ascatter_3d(
        self,
        *,
        x: Any = ...,
        y: Any = ...,
        z: Any = ...,
        color: Any = ...,
        symbol: Any = ...,
        size: Any = ...,
        text: Any = ...,
        hover_name: Any = ...,
        hover_data: Any = ...,
        custom_data: Any = ...,
        error_x: Any = ...,
        error_x_minus: Any = ...,
        error_y: Any = ...,
        error_y_minus: Any = ...,
        error_z: Any = ...,
        error_z_minus: Any = ...,
        animation_frame: Any = ...,
        animation_group: Any = ...,
        category_orders: Any = ...,
        labels: Any = ...,
        size_max: int | None = ...,
        color_discrete_sequence: Any = ...,
        color_discrete_map: Any = ...,
        color_continuous_scale: Any = ...,
        range_color: Any = ...,
        color_continuous_midpoint: Any = ...,
        symbol_sequence: Any = ...,
        symbol_map: Any = ...,
        opacity: float | None = ...,
        log_x: bool = ...,
        log_y: bool = ...,
        log_z: bool = ...,
        range_x: Any = ...,
        range_y: Any = ...,
        range_z: Any = ...,
        title: str | None = ...,
        subtitle: str | None = ...,
        template: str | None = ...,
        width: int | None = ...,
        height: int | None = ...,
        **kwargs: Any,
    ) -> Any: ...

    def __call__(
        self,
        *,
        x: Any = ...,
        y: Any = ...,
        z: Any = ...,
        color: Any = ...,
        symbol: Any = ...,
        size: Any = ...,
        text: Any = ...,
        hover_name: Any = ...,
        hover_data: Any = ...,
        custom_data: Any = ...,
        error_x: Any = ...,
        error_x_minus: Any = ...,
        error_y: Any = ...,
        error_y_minus: Any = ...,
        error_z: Any = ...,
        error_z_minus: Any = ...,
        animation_frame: Any = ...,
        animation_group: Any = ...,
        category_orders: Any = ...,
        labels: Any = ...,
        size_max: int | None = ...,
        color_discrete_sequence: Any = ...,
        color_discrete_map: Any = ...,
        color_continuous_scale: Any = ...,
        range_color: Any = ...,
        color_continuous_midpoint: Any = ...,
        symbol_sequence: Any = ...,
        symbol_map: Any = ...,
        opacity: float | None = ...,
        log_x: bool = ...,
        log_y: bool = ...,
        log_z: bool = ...,
        range_x: Any = ...,
        range_y: Any = ...,
        range_z: Any = ...,
        title: str | None = ...,
        subtitle: str | None = ...,
        template: str | None = ...,
        width: int | None = ...,
        height: int | None = ...,
        **kwargs: Any,
    ) -> Any: ...

    def scatter_3d(
        self,
        *,
        x: Any = ...,
        y: Any = ...,
        z: Any = ...,
        color: Any = ...,
        symbol: Any = ...,
        size: Any = ...,
        text: Any = ...,
        hover_name: Any = ...,
        hover_data: Any = ...,
        custom_data: Any = ...,
        error_x: Any = ...,
        error_x_minus: Any = ...,
        error_y: Any = ...,
        error_y_minus: Any = ...,
        error_z: Any = ...,
        error_z_minus: Any = ...,
        animation_frame: Any = ...,
        animation_group: Any = ...,
        category_orders: Any = ...,
        labels: Any = ...,
        size_max: int | None = ...,
        color_discrete_sequence: Any = ...,
        color_discrete_map: Any = ...,
        color_continuous_scale: Any = ...,
        range_color: Any = ...,
        color_continuous_midpoint: Any = ...,
        symbol_sequence: Any = ...,
        symbol_map: Any = ...,
        opacity: float | None = ...,
        log_x: bool = ...,
        log_y: bool = ...,
        log_z: bool = ...,
        range_x: Any = ...,
        range_y: Any = ...,
        range_z: Any = ...,
        title: str | None = ...,
        subtitle: str | None = ...,
        template: str | None = ...,
        width: int | None = ...,
        height: int | None = ...,
        **kwargs: Any,
    ) -> Any: ...