from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from memframe.db_manager.context import ContextManager


class MemFrame(ContextManager):
    connection_type: str
    conn_params: Dict[str, Any]
    _active_id: Optional[str]
    deep_cache: Optional[bool]

    def __init__(
        self,
        connection_type: str = "local",
        connection_params: Optional[Dict[str, Any]] = None,
        deep_cache: Optional[bool] = None,
    ) -> None: ...

    async def aconnect(self) -> None: ...
    def connect(self) -> None: ...

    async def alist_tables(self) -> List[Dict[str, str]]: ...
    def list_tables(self) -> List[Dict[str, str]]: ...

    async def aset_active(self, data_id: str) -> str: ...
    def set_active(self, data_id: str) -> str: ...

    async def aget_active_table(self) -> Optional[str]: ...
    def get_active_table(self) -> Optional[str]: ...

    async def adelete_table(self, data_id: Optional[str] = ..., filename: Optional[str] = ...) -> None: ...
    def delete_table(self, data_id: Optional[str] = ..., filename: Optional[str] = ...) -> None: ...

    async def alist_operations(self, data_id: Optional[str] = ...) -> List[Dict[str, Any]]: ...
    def list_operations(self, data_id: Optional[str] = ...) -> List[Dict[str, Any]]: ...

    async def aretrieve_operation(self, data_id: str, opidx: int) -> str: ...
    def retrieve_operation(self, data_id: str, opidx: int) -> str: ...

    async def aupload_csv(self, file_path: Union[str, Path], dtypes: Optional[Dict[str, str]] = ...) -> ContextManager: ...
    def upload_csv(self, file_path: Union[str, Path], dtypes: Optional[Dict[str, str]] = ...) -> ContextManager: ...

    async def aupload_parquet(self, file_path: Union[str, Path], dtypes: Optional[Dict[str, str]] = ...) -> ContextManager: ...
    def upload_parquet(self, file_path: Union[str, Path], dtypes: Optional[Dict[str, str]] = ...) -> ContextManager: ...

    async def aupload_df(self, df: Any, filename: Optional[str] = ..., dtypes: Optional[Dict[str, str]] = ...) -> ContextManager: ...
    def upload_df(self, df: Any, filename: Optional[str] = ..., dtypes: Optional[Dict[str, str]] = ...) -> ContextManager: ...

    def memFrame(self, data_id: Optional[str] = ..., data: Any = ..., columns: Optional[List[str]] = ...) -> ContextManager: ...
    def _ops(self, data_id: Optional[str] = ..., data: Any = ..., columns: Optional[List[str]] = ...) -> ContextManager: ...

    async def close(self) -> None: ...

    async def __aenter__(self) -> MemFrame: ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
