from __future__ import annotations

from typing import Any
from db_manager.ops import OpsManager


class OpsWrapper(OpsManager):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    async def aconnect(self) -> None: ...
    def connect(self) -> None: ...

    async def alist_tables(self) -> list[dict[str, str]]: ...
    def list_tables(self) -> list[dict[str, str]]: ...

    async def aset_active(self, data_id: str) -> str: ...
    def set_active(self, data_id: str) -> str: ...

    async def aget_active_table(self) -> str | None: ...
    def get_active_table(self) -> str | None: ...

    async def adelete_table(
        self, data_id: str | None = None, filename: str | None = None
    ) -> None: ...
    def delete_table(
        self, data_id: str | None = None, filename: str | None = None
    ) -> None: ...

    async def alist_operations(self, data_id: str | None = None) -> list[dict[str, Any]]: ...
    def list_operations(self, data_id: str | None = None) -> list[dict[str, Any]]: ...

    async def aretrieve_operation(self, data_id: str, opidx: int) -> str: ...
    def retrieve_operation(self, data_id: str, opidx: int) -> str: ...
