import io
import logging
from typing import Any, Dict, List, Optional, Tuple, TYPE_CHECKING

import pyarrow as pa
import pyarrow.csv as pcsv

from memframe.core.ingestion.upload.base import Uploader

if TYPE_CHECKING:
    pass


logger = logging.getLogger("memFrame")
logger.setLevel(logging.INFO)
if not logger.handlers:
    handler = logging.StreamHandler()
    handler.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s"))
    logger.addHandler(handler)

class PostgresUploader(Uploader):
    """PostgreSQL-specific upload implementation."""

    def __init__(self, backend):
        self._backend = backend
        self._type_detector = backend._type_detector

    async def create_schema_if_not_exists(self, schema_name: str) -> None:
        await self.execute(f"CREATE SCHEMA IF NOT EXISTS {schema_name}")

    @property
    def backend(self):
        return self._backend

    @property
    def _placeholder(self):
        return self._backend.placeholder

    def get_upload_table_name(self, data_id: str) -> str:
        return data_id

    def _memframe_from_data_id(self, data_id: str):
        from memframe.db_manager.context import ContextManager
        return ContextManager(self, data_id=data_id)

    async def _resolve_encoding(self, file_path: str) -> str:
        return await self._backend._resolve_encoding(file_path)

    def _split_qualified_table_name(self, table_name: str) -> Tuple[Optional[str], str]:
        return self._backend._split_qualified_table_name(table_name)

    # ── Table creation: All TEXT ─────────────────────────────────
    async def _create_final_table_all_text_postgres(self, table_name: str, columns: List[str]) -> None:
        col_defs = ", ".join(f'"{col}" TEXT' for col in columns)
        await self.execute(f'CREATE TABLE {table_name} ({col_defs})')

    # ── PyArrow Stream Upload ───────────────────────────────────
    async def _insert_arrow_table_postgres(self, table_name: str, arrow_table: pa.Table) -> None:
        await self._insert_arrow_table_postgres_impl(table_name, arrow_table, arrow_table.schema.names)

    async def _insert_arrow_table_postgres_impl(self, final_table: str, arrow_table: pa.Table, columns: List[str]) -> None:
        full_table = arrow_table.rename_columns(columns)
        buf = io.BytesIO()
        # Use PyArrow's native C++ CSV writer (blazing fast)
        pcsv.write_csv(full_table, buf)
        buf.seek(0)
        buf.readline()  # Skip the header row generated by PyArrow
        schema_name, raw_table = self._split_qualified_table_name(final_table)
        await self._backend.pool.copy_to_table(
            raw_table,
            source=buf,
            columns=columns,
            schema_name=schema_name,
            format="csv",
            header=False,
            encoding="UTF8",
        )
  
    # ── Sampling ────────────────────────────────────────────────
    async def _fetch_arrow_sample_postgres(self, table_name: str, columns: List[str], limit: int) -> pa.Table:
        col_str = ", ".join(self._quote_identifier(c) for c in columns)
        rows = await self._backend.pool.fetch(f"SELECT {col_str} FROM {table_name} LIMIT {limit}")
        data = {col: [row[i] for row in rows] for i, col in enumerate(columns)}
        return pa.Table.from_pydict(data)

    # ── Table Casting ───────────────────────────────────────────
    async def _cast_table_in_place_postgres(self, final_table: str, columns: List[str], schema: Dict[str, Dict[str, Any]]) -> None:
        schema_name, raw_table = self._split_qualified_table_name(final_table)
        tmp_table = f'{schema_name}."{raw_table}_tmp"'
        
        col_defs = []
        for col in columns:
            target_type = schema.get(col, {}).get("postgres_type", "TEXT")
            col_defs.append(f'"{col}" {target_type}')
        await self.execute(f'CREATE TABLE {tmp_table} ({", ".join(col_defs)})')
        
        select_parts = []
        for col in columns:
            target_type = schema.get(col, {}).get("postgres_type", "TEXT")
            select_parts.append(self._build_safe_cast_postgres(col, target_type))
        await self.execute(f'INSERT INTO {tmp_table} SELECT {", ".join(select_parts)} FROM {final_table}')
        
        await self.drop_table(final_table)
        await self.execute(f'ALTER TABLE {tmp_table} RENAME TO {self._quote_identifier(raw_table)}')